import path from "node:path";
import { readFile } from "node:fs/promises";

export type AvatarTone = {
  background: string;
  accent: string;
  skin: string;
  hair: string;
  clothing: string;
  shirt: string;
  glasses?: boolean;
  cap?: boolean;
  image?: string;
  title?: string;
};

export type PortfolioContent = {
  page: {
    avatarOverlap: string;
    avatarPrimary: string;
    avatarSecondary: string;
    background: string;
    description: string;
    name: string;
    stackShiftX: string;
    stackShiftY: string;
    title: string;
  };
  avatars: AvatarTone[];
};

const defaultContent: PortfolioContent = {
  page: {
    avatarOverlap: "clamp(6px, 2.4vw, 34px)",
    avatarPrimary: "clamp(84px, 28vw, 364px)",
    avatarSecondary: "clamp(42px, 14vw, 182px)",
    background: "#fcfaf5",
    description: "Generated by create next app",
    name: "Lokesh Yarramallu",
    stackShiftX: "clamp(-40px, -1.5vw, -12px)",
    stackShiftY: "clamp(32px, 8vh, 110px)",
    title: "Create Next App",
  },
  avatars: [
    {
      background: "#aebdb8",
      accent: "#f3e7d9",
      skin: "#d8a57f",
      hair: "#5b3a25",
      clothing: "#dfd9cf",
      shirt: "#d6d0c7",
      title: "Avatar 1",
    },
    {
      background: "#d3c2b0",
      accent: "#eef2f1",
      skin: "#c89b7f",
      hair: "#9fb0b2",
      clothing: "#1e1f29",
      shirt: "#28303b",
      glasses: true,
      title: "Avatar 2",
    },
    {
      background: "#c3ccc7",
      accent: "#eef3f1",
      skin: "#c99c78",
      hair: "#2a2625",
      clothing: "#d9e6eb",
      shirt: "#b8ccd8",
      glasses: true,
      title: "Avatar 3",
    },
    {
      background: "#a8bcc1",
      accent: "#eff2f0",
      skin: "#b89a81",
      hair: "#2d2931",
      clothing: "#e1ddd6",
      shirt: "#bdbab4",
      glasses: true,
      title: "Avatar 4",
    },
    {
      background: "#b6c8c6",
      accent: "#f1f1ea",
      skin: "#d8ae86",
      hair: "#7a5537",
      clothing: "#9ab0b8",
      shirt: "#d7dce0",
      cap: true,
      title: "Avatar 5",
    },
  ],
};

function parseBoolean(value: string) {
  return value.toLowerCase() === "true";
}

function parseSectionEntries(entries: Record<string, string>) {
  return {
    accent: entries.accent,
    avatarOverlap: entries.avatar_overlap,
    avatarPrimary: entries.avatar_primary,
    avatarSecondary: entries.avatar_secondary,
    background: entries.background,
    clothing: entries.clothing,
    description: entries.description,
    glasses: entries.glasses ? parseBoolean(entries.glasses) : undefined,
    hair: entries.hair,
    image: entries.image || undefined,
    name: entries.name,
    skin: entries.skin,
    shirt: entries.shirt,
    stackShiftX: entries.stack_shift_x,
    stackShiftY: entries.stack_shift_y,
    title: entries.title,
    cap: entries.cap ? parseBoolean(entries.cap) : undefined,
  };
}

function parsePortfolioMarkdown(markdown: string): PortfolioContent {
  const sections: Record<string, Record<string, string>> = {};
  let currentSection = "";

  for (const rawLine of markdown.split(/\r?\n/)) {
    const line = rawLine.trim();

    if (!line || line.startsWith("<!--") || line.startsWith("# ")) {
      continue;
    }

    if (line.startsWith("## ")) {
      currentSection = line.slice(3).trim().toLowerCase();
      sections[currentSection] = sections[currentSection] ?? {};
      continue;
    }

    const separatorIndex = line.indexOf(":");
    if (separatorIndex === -1 || !currentSection) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim().toLowerCase();
    const value = line.slice(separatorIndex + 1).trim();
    sections[currentSection][key] = value;
  }

  const page = parseSectionEntries(sections.page ?? {});
  const avatarSections = Object.entries(sections)
    .filter(([sectionName]) => /^avatar\s+\d+$/i.test(sectionName))
    .sort(([a], [b]) => Number(a.match(/\d+/)?.[0] ?? 0) - Number(b.match(/\d+/)?.[0] ?? 0))
    .map(([, entries], index) => {
      const parsed = parseSectionEntries(entries);
      return {
        background: parsed.background,
        accent: parsed.accent,
        skin: parsed.skin,
        hair: parsed.hair,
        clothing: parsed.clothing,
        shirt: parsed.shirt,
        glasses: parsed.glasses,
        cap: parsed.cap,
        image: parsed.image,
        title: parsed.title || `Avatar ${index + 1}`,
      } satisfies AvatarTone;
    });

  const resolvedPage = {
    avatarOverlap: page.avatarOverlap || defaultContent.page.avatarOverlap,
    avatarPrimary: page.avatarPrimary || defaultContent.page.avatarPrimary,
    avatarSecondary: page.avatarSecondary || defaultContent.page.avatarSecondary,
    background: page.background || defaultContent.page.background,
    description: page.description || defaultContent.page.description,
    name: page.name || defaultContent.page.name,
    stackShiftX: page.stackShiftX || defaultContent.page.stackShiftX,
    stackShiftY: page.stackShiftY || defaultContent.page.stackShiftY,
    title: page.title || defaultContent.page.title,
  };

  const resolvedAvatars =
    avatarSections.length > 0 ? avatarSections : defaultContent.avatars;

  return {
    page: resolvedPage,
    avatars: resolvedAvatars,
  };
}

export async function loadPortfolioContent(): Promise<PortfolioContent> {
  try {
    const filePath = path.join(process.cwd(), "lokesh.md");
    const markdown = await readFile(filePath, "utf8");
    return parsePortfolioMarkdown(markdown);
  } catch {
    return defaultContent;
  }
}
